config/routes.rb
Readtome::Application.routes.draw do
  get "/" => "books#index"
  resources :books
  resources :chapters
  resources :playlists do
    member do
      get 'choose'
      get 'play'
    end
  end
  resources :playlist_items

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :chapters
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    if params.has_key?(:status)
      @current_status = params[:status]
    elsif session.has_key?(:recent_status)
      @current_status = session[:recent_status]
    else
      @current_status = 'Read'
    end
    session[:recent_status] = @current_status
    @statuses = %w{Unread Reading Read}
    @books = Hash.new()
    @statuses.each do |status|
      @books[status] = Book.find(:all, :order => "ordering", :conditions => {:status => status})
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])
    @book.status = "Unread"

    respond_to do |format|
      if @book.save
        @book.ordering = @book.id
        @book.save
        format.html { redirect_to @book, :notice => 'Book was successfully created.' }
        format.json { render :json => @book, :status => :created, :location => @book }
      else
        format.html { render :action => "new" }
        format.json { render :json => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])
    if params[:book][:complete]
      params[:book].delete(:complete)
      @book.status = "Read"
    end

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, :notice => 'Book was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :ok }
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div style="padding: 10px">
  <h3>Editing book</h3>

  <%= render 'form' %>

  <%= link_to 'Show', @book %> |
  <%= link_to 'Back', books_path %>
</div>

app/views/books/index.html.erb
<ul class="tabs">
  <% @statuses.each do |status| %>
    <li <% if status == @current_status %> class="selected" <% end %>><%= link_to "#{status} (#{@books[status].length})", books_path(:status => status) %></li>
  <% end %>
</ul>

<ul class="list">
  <% @books[@current_status].each do |book| %>
    <li><%= link_to book.title, book %> <%= book.author %></li>
  <% end %>
  <li class="last"><%= link_to 'New Book', new_book_path %></li>
</ul>

<br />

app/views/books/new.html.erb
<div style="padding: 10px">
  <h3>New book</h3>

  <%= render 'form' %>

  <%= link_to 'Back', books_path %>
</div>

app/views/books/show.html.erb
<div style="padding: 10px">
  <p id="notice"><%= notice %></p>
  <h3><%= @book.title %></h3>
  <h5>by <%= @book.author %></h5>

  <p>This book
  <% if @book.status == "Unread" %>
    has not been
  <% elsif @book.status == "Reading" %>
    is being
  <% else %>
    has been
  <% end %>
  read.</p>

  <ul class="list">
    <% @book.chapters.each do |chapter| %>
      <li>
		<% if current_playlist.playlist_items.none? {|item| item.chapter == chapter } %>
		  <%= link_to("+", "#{playlist_items_path}?chapter_id=#{chapter.id}&playlist_id=#{current_playlist.id}", :method => :post, :remote => true, :chapter_playlist_link => chapter.id) %>
		<% else %>
		  <%= link_to("-", current_playlist.playlist_items.find_by_chapter_id(chapter.id), :method => :delete, :remote => true, :chapter_playlist_link => chapter.id) %>
		<% end %>
		<%= chapter.displayed_track_length %>
		<%= link_to chapter.name, "/ReadToMe#{chapter.track.url}" %>
		<div class="right">
		  <%= link_to 'Edit', edit_chapter_path(chapter) %>
		</div>
      </li>
    <% end %>
    <li class="last"><%= link_to "Add a chapter", new_chapter_path(:book_id => @book.id) %></li>
  </ul>

  <% if @book.status == "Reading" %>
    <p>
      <%= form_for @book do |f| %>
        <%= f.hidden_field :complete, :value => 1 %>
	<%= f.submit 'Complete' %>
      <% end %>
    </p>
  <% end %>

  <%= link_to 'Edit', edit_book_path(@book) %> |
  <%= link_to 'Back', books_path %>
  <div class="right">
    <%= link_to 'Destroy', @book, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>