config/routes.rb
Readtome::Application.routes.draw do
  get "/" => "books#index"
  resources :books
  resources :chapters
  resources :playlists do
    member do
      get 'choose'
      get 'play'
    end
  end
  resources :playlist_items

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  attr_accessible :name
  has_many :playlist_items
  has_attached_file :mp3
end

app/controllers/playlists_controller.rb
require 'tempfile'

class PlaylistsController < ApplicationController
  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @playlists }
    end
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/new
  # GET /playlists/new.json
  def new
    @playlist = Playlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/1/edit
  def edit
    @playlist = Playlist.find(params[:id])
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(params[:playlist])

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render json: @playlist, status: :created, location: @playlist }
      else
        format.html { render action: "new" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /playlists/1
  # PUT /playlists/1.json
  def update
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      if @playlist.update_attributes(params[:playlist])
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to playlists_url }
      format.json { head :no_content }
    end
  end

  def choose
    session[:playlist] = Playlist.find(params[:id])
    redirect_to playlists_url
  end

  def play
    @playlist = Playlist.find(params[:id])
    unless @playlist.mp3_file_name
      outfile = Tempfile.new("playlist#{params[:id]}")
      system("cat #{@playlist.playlist_items.map {|item| item.chapter.track.path}.join(" ")} > #{outfile.path}.mp3") or raise "problem with system"
      @playlist.mp3 = File.open("#{outfile.path}.mp3")
      @playlist.save!
    end
    redirect_to "/ReadToMe#{@playlist.mp3.url}"
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<h1>Playlists</h1>

<ul class="list">
  <% @playlists.each do |playlist| %>
    <li>
	  <%= link_to playlist.name, playlist %>
	  <div class="right"><%= link_to "choose", choose_playlist_path(playlist) %></div>
	</li>
  <% end %>
  <li class="last"><%= link_to 'New Playlist', new_playlist_path %></li>
</ul>

<br />

app/views/playlists/new.html.erb
<h1>New playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<div style="padding: 10 px">
  <p id="notice"><%= notice %></p>
  <h3><%= @playlist.name %></h3>

  <ul class="list">
	<% @playlist.playlist_items.each do |playlist_item| %>
	  <li<% if playlist_item == @playlist.playlist_items.last %> class="last"<% end %>>
		<%= playlist_item.chapter.displayed_track_length %>
		<%= playlist_item.chapter.book.title %>
		<%= playlist_item.chapter.name %>
		<div class="right">
		  <%= link_to 'Remove', playlist_item, :method => :delete %>
		</div>
	  </li>
	<% end %>
  </ul>

  <%= link_to 'Edit', edit_playlist_path(@playlist) %> |
  <%= link_to 'Back', playlists_path %>
  <div class="right">
	<%= link_to 'Destroy', @playlist, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>